### ISSUE TITLE
strange path

### ISSUE THREAD

**Issue by marekdyjor** [Porocyonak/Open2Nord#1]
I got strange path to config files       there are double "\"

"Congratulations! We have found the best server pl22.nordvpn.com with a ping of 17.0
Copying config file over to OpenVPN...
-------------------------
Critical Error! Shutting down program.
Problem description:
[Errno 2] No such file or directory: 'D:\\Program Files\\OpenVPN\\bin\\config\\pl22.nordvpn.com.udp.ovpn'"

**Comment by Porocyonak** [comment]
~~Sorry for the late reply, try moving your OpenVPN folder to a place that doesn't have a space in the directory~~

~like instead of D:\Program Files\... make like D:\Programs\...~
~I know for sure batch will fail somewhere when there are spaces in the directory, so maybe that will fix something.~

~I know if the code can't find the config file it will take a different one, but that didn't happen so I can only think that the directory might be what's screwing it up.~~

**Comment by Porocyonak** [comment]
Wait nevermind that doesn't make any sense, sorry one second

**Comment by Porocyonak** [comment]
Oh yeah your data.txt 'OpenVPN directory' location is wrong, it should point to the folder itself -- I'm assuming its currently:
D:\Program Files\OpenVPN\bin
it should be
D:\Program Files\OpenVPN

this should almost certainly fix it

**Comment by marekdyjor** [comment]
Thanks a will try it

Marek d

sob., 22 wrz 2018, 05:39 użytkownik Porocyonak <notifications@github.com>
napisał:

**Comment by Porocyonak** [comment]
Cool, let me know if it fixed the issue
